const ADD_FILE = "ADD_FILE";
const FILE_ANALYSE = "FILE_ANALYSE";
const SET_CURRENT = "SET_CURRENT";
const PROCESS_TEXT = "PROCESS_TEXT";
const REPLACE_TEXT = "REPLACE_TEXT";
const TOGGLE_MODAL = "TOGGLE_MODAL";
const SET_LOADING = "SET_LOADING";
const SET_LOADING_DONE = "SET_LOADING_DONE";

export {
  ADD_FILE,
  FILE_ANALYSE,
  SET_CURRENT,
  PROCESS_TEXT,
  REPLACE_TEXT,
  TOGGLE_MODAL,
  SET_LOADING,
  SET_LOADING_DONE,
};
