const ADD_FILE = "ADD_FILE";
const FILE_ANALYSE = "FILE_ANALYSE";
const SET_CURRENT = "SET_CURRENT";
const PROCESS_TEXT = "PROCESS_TEXT";
const REPLACE_TEXT = "REPLACE_TEXT";

export { ADD_FILE, FILE_ANALYSE, SET_CURRENT, PROCESS_TEXT, REPLACE_TEXT };
